version: "3"
services:
  dev:
    image: node:14-alpine
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
    restart: always
    ports:
      - 57842:3000
    depends_on:
      - file_server
    env_file: .env

  file_server:
    image: node:14-alpine
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service/file_server
    working_dir: /usr/src/service/file_server
    command: npm run dev
    ports:
      - 3001:3001
    depends_on:
      - database
    env_file: .env

  unit:
    image: node:14-alpine
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run test
    ports:
      - 3000:3000
    env_file: .env

  coverage:
    image: node:14-alpine
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run coverage
    depends_on:
      - database
    ports:
      - 3000:3000
    env_file: .env

  integration:
    image: node:14-alpine
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run test integration
    depends_on:
      - database
    ports:
      - 3000:3000
    env_file: .env

  database:
    image: dannyben/alpine-mongo:latest
    restart: always
    ports:
      - 58703:27017
    volumes:
      - mongodatabase:/data/db
    command: mongod --auth --port 27017 --dbpath /data/db --bind_ip 0.0.0.0

volumes:
  nodemodules:
    external: true
  mongodatabase:
    external: true
