#!/bin/bash
CUR=$(dirname $(readlink -f $0))

case "$1" in
    "-d")
        docker-compose -f $CUR/../docker-compose.yml up dev -d
        ;;
    *)
        docker-compose -f $CUR/../docker-compose.yml up dev
        ;;
esac