#!/bin/bash
CUR=$(dirname $(readlink -f $0))

case "$1" in
    "-d")
        docker-compose -f $CUR/../docker-compose.yml up --detach dev 
        ;;
    *)
        docker-compose -f $CUR/../docker-compose.yml up dev
        ;;
esac
